# Generated by Django 5.1.15 on 2026-09-06 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmiPlan',
            fields=[
                ('id', models.SlugField(max_length=32, primary_key=True, serialize=False)),
                ('tenure_months', models.PositiveIntegerField()),
                ('annual_interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('processing_fee_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('recommended', models.BooleanField(default=False)),
                ('tag', models.CharField(blank=True, default='', max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('position', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['position', 'tenure_months'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.SlugField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=120)),
                ('category', models.CharField(max_length=80)),
                ('thumbnail', models.URLField()),
                ('description', models.TextField(blank=True)),
                ('images', models.JSONField(default=list)),
                ('highlights', models.JSONField(default=list)),
                ('specifications', models.JSONField(default=list)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('rating_count', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.SlugField(max_length=80, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=160)),
                ('attributes', models.JSONField(default=dict)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('mrp', models.DecimalField(decimal_places=2, max_digits=12)),
                ('in_stock', models.BooleanField(default=True)),
                ('image', models.URLField(blank=True, default='')),
                ('position', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='marketplace.product')),
            ],
            options={
                'ordering': ['position', 'price'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.CharField(editable=False, max_length=40, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=200)),
                ('variant_label', models.CharField(max_length=160)),
                ('principal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monthly_emi', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tenure_months', models.PositiveIntegerField()),
                ('total_payable', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(default='CONFIRMED', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='marketplace.emiplan')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='marketplace.product')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='marketplace.productvariant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
